apiVersion: v1
kind: Service
metadata:
  name: jenkins-master
  labels:
    app: jenkins-master
spec:
  type: NodePort
  ports:
    - name: jenkins-master-web
      nodePort: 30800
      port: 8080
      targetPort: 8080
    - name: jenkins-master-tunnel
      nodePort: 30801
      port: 50000
      targetPort: 50000
  selector:
    app: jenkins-master
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-master-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins-master
    spec:
      containers:
        # - image: jenkins/jenkins:lts
        - image: ec2-52-80-8-7.cn-north-1.compute.amazonaws.com.cn:30500/jenkins-master:1.5.0
          imagePullPolicy: IfNotPresent
          name: jenkins-master
          ports:
            - name: web
              containerPort: 8080
            - name: tunnel
              containerPort: 50000
          #       volumeMounts:
          #        - mountPath: /var/run/docker.sock
          #          name: docker-socket
          #        - mountPath: /usr/bin/docker
          #          name: docker-bin
          #        - mountPath: /var/jenkins_home
          #          name: jenkins-home
          env:
            - name: DOCKER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: registry-generic-secret
                  key: username
            - name: DOCKER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: registry-generic-secret
                  key: password
#      volumes:
#      - name: docker-socket
#        hostPath:
#          path: /var/run/docker.sock
#      - name: docker-bin
#        hostPath:
#          path: /usr/bin/docker
#      - name: jenkins-home
#        hostPath:
#          path: /home/ubuntu/jenkins_home/
