apiVersion: v1
kind: Service
metadata:
  name: jenkins-slave
  labels:
    app: jenkins-slave
spec:
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: jenkins-slave
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-slave
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins-slave
    spec:
      containers:
      - image: ec2-52-80-8-7.cn-north-1.compute.amazonaws.com.cn:30500/jenkins-slave:1.0.0
        imagePullPolicy: IfNotPresent
        name: jenkins-slave
        env:
        - name: JENKINS_URL
          value: http://jenkins:8080
        - name: JENKINS_SLAVE_ADDRESS
          value: http://jenkins-tunnel:50000
          ports:
        - containerPort: 8081
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-socket
        - mountPath: /usr/bin/docker
          name: docker-bin
        env:
        - name: DOCKER_USERNAME
          valueFrom:
            secretKeyRef:
              name: registry-generic-secret
              key: username
        - name: DOCKER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: registry-generic-secret
              key: password
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
      - name: docker-bin
        hostPath:
          path: /usr/bin/docker
